In [ ]:
#Install preprocessing with Keras

! pip install Keras
! pip install Keras-Preprocessing
! pip install keras.processing

ERROR: Could not find a version that satisfies the requirement keras.processing (from versions: none)
ERROR: No matching distribution found for keras.processing


In [ ]:
#Load all the necessary libraries
#Load tensorflow.keras.models
#Load the dataset using from keras.datasets import imdb

import numpy as np
import pandas as pd
from tensorflow.keras.datasets import imdb


In [ ]:
#code refernce https://keras.io/api/datasets/imdb
#since the ouput for the imdb.load_data is x_train, x_test and y_train, y_test
# warnings for VisibleDeprecationWarning resolved via https://stackoverflow.com/questions/66414449/importing-imdb-dataset-from-keras-dataset
(X_train, y_train), (X_test, y_test) = imdb.load_data(num_words=10000)

#

<string>:6: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/datasets/imdb.py:159: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  x_train, y_train = np.array(xs[:idx]), np.array(labels[:idx])
/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/datasets/imdb.py:160: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 

In [ ]:
#Print the number of unique categories for the target variable
#Print the average review length
#Print the standard deviation
# for all the three questions it has not beeen mentioned that this has to be test data or training data so i am exploring this on the training data

#print(type(X_train))
# code refernce https://numpy.org/doc/stable/reference/generated/numpy.unique.html

a=np.unique(y_train)
print('the unique categories are',a)

#new_lst=[]
#for i in X_train:
 # new_lst.append(len(i))
      
#print(len(new_lst))
#new_train=np.array(new_lst)

#using numpy operations
#code refence https://www.geeksforgeeks.org/compute-the-mean-standard-deviation-and-variance-of-a-given-numpy-array/
movie_len=[len(i) for i in X_train]
avg_mv_len=np.mean(movie_len)
print('the average lenght of the movies is',avg_mv_len)
std_mov=np.std(movie_len)
print('the standard devistion of the of the movies dataset is',std_mov)

the unique categories are [0 1]
the average lenght of the movies is 238.71364
the standard devistion of the of the movies dataset is 176.49367364852034


In [ ]:
#Vectorize sequences and dimension with a size of 10,000
#code refernce https://www.javaer101.com/en/article/18836089.html
#https://www.geeksforgeeks.org/vectorization-in-python/
#https://colab.research.google.com/drive/1GSsIKJ8Uqy2Qi6TOBPlWvCSZmMLIlhh6

def vector_sequence(data, dimension=10000):
    vector = np.zeros((len(data), dimension))
    for i, data in enumerate(data):
        vector[i,data] = 1.
    return vector

train_data = vector_sequence(X_train)

print(train_data.shape)

test_data = vector_sequence(X_test)

print(test_data.shape)

#Make sure the test and train variables represent 10,000 observations

print('number of of observations in the test data',len(test_data[0]))
print('number of of observations in the train data',len(train_data[0]))



(25000, 10000)
(25000, 10000)
number of of observations in the test data 10000
number of of observations in the train data 10000


In [ ]:
#Import Sequential, Flatten, Dropout, and Dense from tensorflow.keras.models
# Flatten, Dropout, and Dense  are in the tensorflow.keras.layers not the tensorflow.keras.models reference https://stackoverflow.com/questions/59388162/importerror-cannot-import-name-sequential-from-keras-models
import tensorflow.keras.models
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten, Dense, Dropout

#code refernce for dropout from https://keras.io/api/layers/regularization_layers/dropout/ i am setting  all of them at 0.5 and putting all the default parameters from the defination in the keras library
model = Sequential()
# code refrence for input shape https://keras.io/api/layers/core_layers/dense/ each row has a batch of 10000 obeservations
model.add(Dense(50, activation = "relu",input_shape=(10000, )))
model.add(Dropout(0.2, noise_shape=None, seed=None))
model.add(Dense(1024, activation = "relu"))
model.add(Dropout(0.2, noise_shape=None, seed=None))
model.add(Dense(2, activation = "relu"))
model.add(Dense(1, activation = "relu"))

model.summary()


Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 50)                500050    
_________________________________________________________________
dropout (Dropout)            (None, 50)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 1024)              52224     
_________________________________________________________________
dropout_1 (Dropout)          (None, 1024)              0         
_________________________________________________________________
dense_2 (Dense)              (None, 2)                 2050      
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 3         
Total params: 554,327
Trainable params: 554,327
Non-trainable params: 0
__________________________________________________

In [ ]:
#Use the following parameters with an ‘adam’ optimizer and ‘binary_crossentropy’ loss function
#code refernce https://colab.research.google.com/drive/1B6TLosBa-q9d9knwlRkvGokv2W2MGtsH
model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

#Compile, train, and evaluate the model with epochs=20, batch_size=512, validation_data=(test_x,test_y)
model.fit(train_data,y_train,epochs=20,batch_size=512,validation_data=(test_data,y_test))

Epoch 1/20
49/49 [==============================] - 5s 97ms/step - loss: 1.4603 - accuracy: 0.5636 - val_loss: 0.4487 - val_accuracy: 0.8439
Epoch 2/20
49/49 [==============================] - 4s 77ms/step - loss: 0.3563 - accuracy: 0.8805 - val_loss: 0.3747 - val_accuracy: 0.8725
Epoch 3/20
49/49 [==============================] - 4s 77ms/step - loss: 0.2442 - accuracy: 0.9347 - val_loss: 0.4102 - val_accuracy: 0.8630
Epoch 4/20
49/49 [==============================] - 4s 77ms/step - loss: 0.1910 - accuracy: 0.9441 - val_loss: 0.5272 - val_accuracy: 0.8689
Epoch 5/20
49/49 [==============================] - 4s 79ms/step - loss: 0.1451 - accuracy: 0.9693 - val_loss: 0.5758 - val_accuracy: 0.8687
Epoch 6/20
49/49 [==============================] - 4s 79ms/step - loss: 0.1188 - accuracy: 0.9819 - val_loss: 0.6142 - val_accuracy: 0.8616
Epoch 7/20
49/49 [==============================] - 4s 78ms/step - loss: 0.0971 - accuracy: 0.9857 - val_loss: 0.7092 - val_accuracy: 0.8630
Epoch 8/20
49

Epoch 20/20
49/49 [==============================] - 4s 79ms/step - loss: 0.0866 - accuracy: 0.9916 - val_loss: 1.2185 - val_accuracy: 0.8661

At the 20th Epoch the accuracy of the model is 0.9916  and the loss is 0.0866 which means our model  is good  and highly accurate and the cross validation accuracy score of 0.8661 confirms the same 

In [ ]:
#Use the ‘yelp_labelled.txt’
yelp_data = pd.read_csv('/content/yelp_labelled.txt', delimiter = "\t")
print('the number of rows and columns are',yelp_data.shape)
yelp_data.head()

the number of rows and columns are (999, 2)


Wow... Loved this place.  1
0                                 Crust is not good.  0
1          Not tasty and the texture was just nasty.  0
2  Stopped by during the late May bank holiday of...  1
3  The selection on the menu was great and so wer...  1
4     Now I am getting angry and I want my damn pho.  0

In [ ]:
#Use ‘sentence’ as feature and ‘label’ as target
yelp_data.columns=['sentence', 'label']


feature =yelp_data['sentence']
target=yelp_data['label']

#Tokenizer with 5,000 words

from keras.preprocessing.text import Tokenizer
from sklearn.model_selection import train_test_split

#since the dision between test data and training data has not been specified i took the value 70/30 
X_train,X_test,y_train,y_test=train_test_split(feature,target,test_size=0.3,random_state=42)
print('the  size of the training data is',len(X_train))
print('the  size of the testing  data is',len(X_test))

#from keras.processing.text import Tokenizer
# code refernce https://datascience.stackexchange.com/questions/37159/understanding-the-effect-of-num-words-of-tokenizer-in-keras
yelp_token = Tokenizer(num_words = 5000)

#code refence for transformation https://stackoverflow.com/questions/51956000/what-does-keras-tokenizer-method-exactly-do

yelp_token.fit_on_texts(X_train)
yelp_token.fit_on_texts(X_test)

#Pad the X_train and X_test values

train_yelp_data=yelp_token.texts_to_sequences(X_train)
test_yelp_data=yelp_token.texts_to_sequences(X_test)

vocab_len=len(yelp_token.word_index)+1
#print(test_yelp_data)
#padding syntax code refence https://realpython.com/python-keras-text-classification/

from keras.preprocessing.sequence import pad_sequences

X_train_yelp = pad_sequences(train_yelp_data,padding='post', maxlen=100)
X_test_yelp = pad_sequences(test_yelp_data,padding='post', maxlen=100)
print(y_train)

y_train=np.array(y_train)
y_test=np.array(y_test)
print(X_train_yelp)


the  size of the training data is 699
the  size of the testing  data is 300
728    1
630    1
394    1
777    0
598    0
      ..
106    1
270    1
860    1
435    1
102    1
Name: label, Length: 699, dtype: int64
[[ 43  13   1 ...   0   0   0]
 [  1 585 293 ...   0   0   0]
 [  6 898   1 ...   0   0   0]
 ...
 [332 104  23 ...   0   0   0]
 [ 85  42 160 ...   0   0   0]
 [  3 183  48 ...   0   0   0]]


In [ ]:
#Use a ‘Sequential()’ model with 
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten, Dense, Dropout
from keras.layers.embeddings import Embedding
from keras.layers import Conv1D, GlobalMaxPool1D

epochs = 20
maxlen = 100
embedding_dim = 50
num_filters = 64
kernel_size = 5
batch_size = 32


#embedding code refrence https://colab.research.google.com/drive/1B6TLosBa-q9d9knwlRkvGokv2W2MGtsH#scrollTo=jVzZ9uKzoY-h
# in the embedding layer the input_dim is 

yelp_model=Sequential()
yelp_model.add(Embedding(input_dim=vocab_len,output_dim=embedding_dim,input_length = maxlen) )
yelp_model.add(Conv1D(filters=num_filters, kernel_size=kernel_size, activation='relu'))
yelp_model.add(GlobalMaxPool1D())
yelp_model.add(Dense(10, activation = "relu"))
yelp_model.add(Dense(1, activation = "relu"))

yelp_model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 100, 50)           103600    
_________________________________________________________________
conv1d (Conv1D)              (None, 96, 64)            16064     
_________________________________________________________________
global_max_pooling1d (Global (None, 64)                0         
_________________________________________________________________
dense_4 (Dense)              (None, 10)                650       
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 11        
Total params: 120,325
Trainable params: 120,325
Non-trainable params: 0
_________________________________________________________________


In [ ]:
#using the default model vocab_len
#Determine the loss, accuracy of the training and testing model
#Use a ‘Sequential()’ model with 

yelp_model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

yelp_model.fit(X_train_yelp,y_train,epochs=20,batch_size=32,validation_data=(X_test_yelp,y_test))

Epoch 1/20
22/22 [==============================] - 1s 29ms/step - loss: 1.4416 - accuracy: 0.4925 - val_loss: 0.6873 - val_accuracy: 0.5267
Epoch 2/20
22/22 [==============================] - 0s 21ms/step - loss: 0.6621 - accuracy: 0.6251 - val_loss: 0.6890 - val_accuracy: 0.5133
Epoch 3/20
22/22 [==============================] - 0s 21ms/step - loss: 0.6109 - accuracy: 0.8012 - val_loss: 0.6726 - val_accuracy: 0.6167
Epoch 4/20
22/22 [==============================] - 0s 21ms/step - loss: 0.5642 - accuracy: 0.9494 - val_loss: 0.6592 - val_accuracy: 0.6267
Epoch 5/20
22/22 [==============================] - 0s 22ms/step - loss: 0.4944 - accuracy: 0.9316 - val_loss: 0.6338 - val_accuracy: 0.6467
Epoch 6/20
22/22 [==============================] - 0s 21ms/step - loss: 0.4075 - accuracy: 0.9447 - val_loss: 0.5860 - val_accuracy: 0.6967
Epoch 7/20
22/22 [==============================] - 0s 21ms/step - loss: 0.2811 - accuracy: 0.9510 - val_loss: 0.5324 - val_accuracy: 0.7333
Epoch 8/20
22

#the training accuracy of the model is 100% and the loss is 0% but the validation accuracy score is 79% and loss is 59% which means the model is a good model but can be enhanced further

In [ ]:
yelp_model.evaluate(X_test_yelp,y_test)

10/10 [==============================] - 0s 4ms/step - loss: 0.5994 - accuracy: 0.7967


[0.5993621349334717, 0.79666668176651]